### ISSUE TITLE
build the project I get this,How can I do?

### ISSUE THREAD

**Issue by sourcealinx** [w4lle/JianDan-React-Native#2]
- What went wrong:
  A problem occurred configuring root project 'JianDanReactNative'.
  > Could not resolve all dependencies for configuration ':classpath'.
  > Could not find any matches for com.facebook.react:gradleplugin:1.0.+ as no versions of com.facebook.react:gradleplugin are available.
   Searched in the following locations:
       file:/Users/Alinx/.m2/repository/com/facebook/react/gradleplugin/maven-metadata.xml
       file:/Users/Alinx/.m2/repository/com/facebook/react/gradleplugin/
       https://jcenter.bintray.com/com/facebook/react/gradleplugin/maven-metadata.xml
       https://jcenter.bintray.com/com/facebook/react/gradleplugin/
   Required by:
       :JianDanReactNative:unspecified

**Comment by w4lle** [comment]
Did you install gradle for building Android project?

**Comment by sourcealinx** [comment]
I had.And I use android studio to build.
Error:Could not find any matches for com.facebook.react:gradleplugin:1.0.+ as no versions of com.facebook.react:gradleplugin are available.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/facebook/react/gradleplugin/maven-metadata.xml
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/facebook/react/gradleplugin/
    file:/Users/Alinx/.m2/repository/com/facebook/react/gradleplugin/maven-metadata.xml
    file:/Users/Alinx/.m2/repository/com/facebook/react/gradleplugin/
    https://jcenter.bintray.com/com/facebook/react/gradleplugin/maven-metadata.xml
    https://jcenter.bintray.com/com/facebook/react/gradleplugin/
Required by:
    :JianDanReactNative:unspecified

**Comment by w4lle** [comment]
and the react native environment ?
https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by sourcealinx** [comment]
I think my environment is ok, because I can run other demos...like ZhiHuDaily-React-Native

**Comment by w4lle** [comment]
Did you run this shell ./build-and-install-react-native-gradle-plugin.sh
then, import the directory JianDanReactNative/android as An Android project with Andorid studio

**Comment by sourcealinx** [comment]
run it, I see that " gradle: command not found".maybe I can't set gradle to system environment.let me try.wait.

**Comment by sourcealinx** [comment]
成功了！真的是gradle环境变量没设。突然发现你也是中国的。还是用中文比较好说。英语太渣了。谢了。刚接触react native 什么都不懂。。。

**Comment by w4lle** [comment]
fuck egg.
看这个 凌晨0:23 (UTC-07:00 休斯顿、底特律时间) 
我还以为是老外。中式英语彼此彼此！

**Comment by sourcealinx** [comment]
哈哈哈。大神以后多多指教。以后遇到问题还得找你请教。来个联系方式呗。

**Comment by w4lle** [comment]
有问题在这里提就可以，大家都能看到
